### ISSUE TITLE
"Maintenance" is too long  

### ISSUE THREAD

**Issue by Dehta-Hun** [M010/monkey-stars#2]
![image](https://github.com/M010/monkey-stars/assets/55526180/0ef4e80e-93f9-4430-b15b-d306140d20a5)
I think that the word Maintenance is too long. If there is multiple links in line it become unclear what is what.

I suggest 🔄 emoji instead

```javascript
link.append(` ⭐ ${stars} | 🔄: ${Math.round(maintenanceScore * 100)}%`); // Use the saved jQuery object

**Comment by M010** [comment]
Thanks! It is a good point. Also it would be great idea to  add it to the readme.md file.

**Comment by M010** [comment]
test link:  https://github.com/M010/monkey-stars
