### ISSUE TITLE
Percentage become over 100 

### ISSUE THREAD

**Issue by Dehta-Hun** [M010/monkey-stars#3]
![image](https://github.com/M010/monkey-stars/assets/55526180/51dac627-aec1-4a29-83f0-4e8eaae7f39f)
I guess it's supposed to be from 1 to 100 % right? Or am I missing something?

**Comment by M010** [comment]
Yeah. It should be. This is a mix of two stats: open/closed issues and  commit activity rate. Please, share the link to the repo.  Then we will check not mixed params. I think it is a good first steps!
